# Generated by Django 2.1.7 on 2019-03-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anti_num', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anti_park',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False)),
                ('occupy', models.BooleanField(default=None)),
                ('license_number', models.CharField(max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'park',
            },
        ),
    ]
