# Generated by Django 2.1.7 on 2019-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiPark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10, null=True)),
                ('anti_num', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'anti_park',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default=None, max_length=25, unique=True, verbose_name='卡号')),
            ],
            options={
                'verbose_name': '卡号',
                'verbose_name_plural': '卡号',
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='InPark',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('inside', models.IntegerField(default=1, null=True, verbose_name='是否为校内车牌')),
                ('license_number', models.CharField(max_length=10, null=True, unique=True, verbose_name='车牌号')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校内临时停车场',
                'verbose_name_plural': '校内临时停车场',
                'db_table': 'in_park',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='开闸指令ID')),
                ('order', models.BooleanField(default=False, verbose_name='开闸指令')),
            ],
            options={
                'verbose_name': '开闸指令管理',
                'verbose_name_plural': '开闸指令管理',
                'db_table': 'open_order',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=None)),
                ('license_number', models.CharField(max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'park',
            },
        ),
        migrations.CreateModel(
            name='ParkTwo',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('inside', models.IntegerField(default=1, null=True, verbose_name='是否为校内车牌')),
                ('license_number', models.CharField(max_length=10, null=True, unique=True, verbose_name='车牌号')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '校内车牌库存',
                'verbose_name_plural': '校内车牌库存',
                'db_table': 'park_two',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_park', models.IntegerField(default=0, verbose_name='已用车位数量')),
                ('out_park', models.IntegerField(default=100, verbose_name='剩余车位数量')),
                ('total', models.IntegerField(default=100, verbose_name='车位总数')),
            ],
            options={
                'verbose_name': '停车场车位数量管理',
                'verbose_name_plural': '停车场车位数量管理',
                'db_table': 'total_park',
            },
        ),
    ]
