# Generated by Django 2.1.7 on 2019-03-30 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='occupy',
            new_name='status',
        ),
    ]
