# Generated by Django 2.1.7 on 2019-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_auto_20190331_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='antipark',
            name='license_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
