# Generated by Django 2.1.7 on 2019-04-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_antipark_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkTwo',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False)),
                ('inside', models.BooleanField(default=None)),
                ('license_number', models.CharField(max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'park_two',
            },
        ),
    ]
