# Generated by Django 2.1.7 on 2019-04-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_auto_20190402_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parktwo',
            name='create_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='parktwo',
            name='inside',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
