# Generated by Django 2.1.7 on 2019-04-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_auto_20190402_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'card',
            },
        ),
    ]
