# Generated by Django 2.1.7 on 2019-04-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_auto_20190406_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parktwo',
            name='inside',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
