# Generated by Django 2.1.7 on 2019-04-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_auto_20190406_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=None, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='parktwo',
            name='license_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
