# Generated by Django 2.1.7 on 2019-04-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_auto_20190406_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPark',
            fields=[
                ('park_id', models.AutoField(primary_key=True, serialize=False)),
                ('inside', models.IntegerField(default=1, null=True)),
                ('license_number', models.CharField(max_length=10, null=True, unique=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'in_park',
            },
        ),
    ]
